apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-extension-decision-maker-cache
  namespace: harikube
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
