# This rule is not used by the project api-extension itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to api-extension.harikube.info resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: api-extension
    app.kubernetes.io/managed-by: kustomize
  name: count-viewer-role
rules:
- apiGroups:
  - api-extension.harikube.info
  resources:
  - counts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api-extension.harikube.info
  resources:
  - counts/status
  verbs:
  - get
